# For full config options, check the docs:
#    docs.serverless.com
#
# AWS SDK Documentation
#    docs.aws.amazon.com/AWSJavaScriptSDK/latest/index.html

service: sanitizeAws
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  timeout: 240
  stage: prod
  environment: ${file(env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:*"
        - "ecs:*"
        - "ebs:*"
        - "s3:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "*"
package:
  include:
    - ../constants.js
    - ../utils.js
functions:
  sanitizeAws:
    handler: handler.sanitizeAws
    name: Sanitize-AWS
    description: Remove unused volumes and snapshots.
    events:
      - schedule: cron(0 1 * * ? *)
