version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - cd ./health-monitor/eth-sync
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - make compile

  post_build:
    commands:
      - echo Build completed on `date`
      - make deploy
