service: doge-murderer
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:*"
        - "ecs:*"
        - "ebs:*"
        - "s3:*"
      Resource: "*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  murder:
    handler: bin/murder
    events:
      - schedule: rate(5 minutes)
