image: node:8.11.3

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - cp ./modules/ethereum/config/config-sample.ts ./modules/ethereum/config/config.ts
    - yarn
    - yarn tsc
    - yarn lint

.deploy_common: &deploy_common
  image: ruby:2.4-alpine
  script:
    - apk update && apk add git
    - git clone https://treyt:"$password"@gitlab.com/ideas-by-nature/devops/awsibn.git
    - cd awsibn
    - bundle install
    - gem build awsibn.gemspec
    - gem install awsibn-1.0.gem
    - awsibn deploy labyrinth minotaur${ENV}

staging-deploy:
  <<: *deploy_common
  stage: deploy
  variables:
    ENV: "staging"
  only:
    refs:
      - staging

dev-deploy:
  <<: *deploy_common
  stage: deploy
  variables:
    ENV: "dev"
  only:
    refs:
      - dev

prod-deploy:
  <<: *deploy_common
  stage: deploy
  variables:
    ENV: "prod"
  only:
    refs:
      - prod
