// ***
// Code (re)generated by go generate; DO NOT EDIT BY HAND;
// Fri Jun 29 11:20:59 MDT 2018

package coin

var Coins = []string{

	"ETH",

	"BCH",

	"ETHPARITY",

	"LTC",

	"ZEC",

	"BTC",

	"DASH",

	"BTG",

	"DOGE",
}
