-- This file is auto-generated and should not be directly modified.

DROP TABLE IF EXISTS "validation_records" CASCADE;
DROP TABLE IF EXISTS "receipts" CASCADE;
DROP TABLE IF EXISTS "transactions" CASCADE;
DROP TABLE IF EXISTS "infos" CASCADE;
DROP TABLE IF EXISTS "internal_transactions" CASCADE;
DROP TABLE IF EXISTS "token_transfers" CASCADE;
DROP TABLE IF EXISTS "tokens" CASCADE;
DROP TABLE IF EXISTS "transaction_logs" CASCADE;
DROP TABLE IF EXISTS "services" CASCADE;
DROP TABLE IF EXISTS "last_blocks" CASCADE;
DROP TABLE IF EXISTS "currencies" CASCADE;
DROP TABLE IF EXISTS "contracts" CASCADE;
DROP TABLE IF EXISTS "blocks" CASCADE;
DROP TABLE IF EXISTS "addresses" CASCADE;
DROP TABLE IF EXISTS "addresses" CASCADE;
CREATE TABLE IF NOT EXISTS "addresses" ("hash" VARCHAR(255) NOT NULL , "balance" DECIMAL NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("hash"));
DROP TABLE IF EXISTS "blocks" CASCADE;
CREATE TABLE IF NOT EXISTS "blocks" ("index" INTEGER NOT NULL , "hash" VARCHAR(255) NOT NULL, "timeMined" TIMESTAMP WITH TIME ZONE NOT NULL, "bloom" TEXT NOT NULL, "coinbase" VARCHAR(255) NOT NULL, "difficulty" BIGINT NOT NULL, "extraData" VARCHAR(255) NOT NULL, "gasLimit" BIGINT NOT NULL, "parentHash" VARCHAR(255) NOT NULL, "receiptsRoot" VARCHAR(255) NOT NULL, "stateRoot" VARCHAR(255) NOT NULL, "transactionsRoot" VARCHAR(255) NOT NULL, "uncleHash" VARCHAR(255) NOT NULL, "gasUsed" BIGINT NOT NULL, "mixHash" VARCHAR(255) NOT NULL, "nonce" VARCHAR(255) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("index"));
CREATE INDEX "blocks_time_mined" ON "blocks" ("timeMined");
DROP TABLE IF EXISTS "contracts" CASCADE;
CREATE TABLE IF NOT EXISTS "contracts" ("address" VARCHAR(255) NOT NULL UNIQUE , "transaction" VARCHAR(255) DEFAULT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, "modified" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("address"));
CREATE INDEX "contracts_address" ON "contracts" ("address");
CREATE INDEX "contracts_transaction" ON "contracts" ("transaction");
DROP TABLE IF EXISTS "currencies" CASCADE;
CREATE TABLE IF NOT EXISTS "currencies" ("id" INTEGER NOT NULL , "name" VARCHAR(255) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, "modified" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
DROP TABLE IF EXISTS "last_blocks" CASCADE;
CREATE TABLE IF NOT EXISTS "last_blocks" ("currency" INTEGER NOT NULL , "blockIndex" BIGINT DEFAULT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, "modified" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("currency"));
DROP TABLE IF EXISTS "services" CASCADE;
CREATE TABLE IF NOT EXISTS "services" ("name" VARCHAR(255) NOT NULL , "state" JSONB DEFAULT NULL, PRIMARY KEY ("name"));
DROP TABLE IF EXISTS "transaction_logs" CASCADE;
CREATE TABLE IF NOT EXISTS "transaction_logs" ("transaction" VARCHAR(255) NOT NULL , "data" TEXT NOT NULL, "index" INTEGER NOT NULL, "removed" BOOLEAN NOT NULL, "topics" JSONB NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("transaction"));
DROP TABLE IF EXISTS "tokens" CASCADE;
CREATE TABLE IF NOT EXISTS "tokens" ("id" VARCHAR(255) NOT NULL , "name" VARCHAR(255) NOT NULL, "totalSupply" DECIMAL NOT NULL, "decimals" SMALLINT NOT NULL, "version" VARCHAR(255) NOT NULL, "symbol" VARCHAR(255) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
DROP TABLE IF EXISTS "token_transfers" CASCADE;
CREATE TABLE IF NOT EXISTS "token_transfers" ("id" BIGINT NOT NULL , "status" SMALLINT NOT NULL, "transaction" VARCHAR(255) NOT NULL, "currency" VARCHAR(255) NOT NULL, "to" VARCHAR(255) DEFAULT NULL, "from" VARCHAR(255) NOT NULL, "amount" DECIMAL NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
CREATE INDEX "token_transfers_to" ON "token_transfers" ("to");
CREATE INDEX "token_transfers_from" ON "token_transfers" ("from");
DROP TABLE IF EXISTS "internal_transactions" CASCADE;
CREATE TABLE IF NOT EXISTS "internal_transactions" ("id" BIGINT NOT NULL , "transaction" VARCHAR(255) NOT NULL, "to" VARCHAR(255) DEFAULT NULL, "from" VARCHAR(255) DEFAULT NULL, "amount" DECIMAL NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
CREATE INDEX "internal_transactions_to" ON "internal_transactions" ("to");
CREATE INDEX "internal_transactions_from" ON "internal_transactions" ("from");
DROP TABLE IF EXISTS "infos" CASCADE;
CREATE TABLE IF NOT EXISTS "infos" ("id" BIGINT NOT NULL , "schemaVersion" VARCHAR(255) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, "modified" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
DROP TABLE IF EXISTS "transactions" CASCADE;
CREATE TABLE IF NOT EXISTS "transactions" ("hash" VARCHAR(255) DEFAULT NULL , "to" VARCHAR(255) DEFAULT NULL, "from" VARCHAR(255) DEFAULT NULL, "amount" DECIMAL NOT NULL, "gasLimit" BIGINT NOT NULL, "gasPrice" DECIMAL NOT NULL, "gasUsed" BIGINT NOT NULL, "nonce" BIGINT NOT NULL, "timeReceived" TIMESTAMP WITH TIME ZONE NOT NULL, "blockIndex" BIGINT NOT NULL, "transactionIndex" INTEGER NOT NULL, "v" VARCHAR(255) NOT NULL, "r" VARCHAR(255) NOT NULL, "s" VARCHAR(255) NOT NULL, "inputData" TEXT NOT NULL, "status" SMALLINT DEFAULT NULL, "cumulativeGasUsed" BIGINT NOT NULL, "postRoot" VARCHAR(255) DEFAULT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("hash"));
CREATE INDEX "transactions_to_block_index" ON "transactions" ("to", "blockIndex");
CREATE INDEX "transactions_from_block_index" ON "transactions" ("from", "blockIndex");
CREATE INDEX "transactions_block_index" ON "transactions" ("blockIndex");
DROP TABLE IF EXISTS "receipts" CASCADE;
CREATE TABLE IF NOT EXISTS "receipts" ("hash" VARCHAR(255) NOT NULL UNIQUE , "cumulativeGasUsed" BIGINT NOT NULL, "postRoot" VARCHAR(255) DEFAULT NULL, "status" SMALLINT DEFAULT NULL, "gasUsed" BIGINT NOT NULL, "logsBloom" TEXT NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("hash"));
DROP TABLE IF EXISTS "validation_records" CASCADE;
CREATE TABLE IF NOT EXISTS "validation_records" ("blockIndex" BIGINT , "valid" BOOLEAN NOT NULL, "data" JSONB NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, "modified" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("blockIndex"));
CREATE INDEX "validation_records_valid" ON "validation_records" ("valid");
INSERT INTO "last_blocks" ("currency","blockIndex","created","modified") VALUES (1, NULL, NOW(), NOW());
INSERT INTO "last_blocks" ("currency","blockIndex","created","modified") VALUES (2, NULL, NOW(), NOW());
INSERT INTO "currencies" ("id","name","created","modified") VALUES (1, 'Bitcoin', NOW(), NOW());
INSERT INTO "currencies" ("id","name","created","modified") VALUES (2, 'Ethereum', NOW(), NOW());
INSERT INTO "services" ("name","state") VALUES ('eth-scan', '{"enabled":true,"blockIndex":0,"interval":60000}');
INSERT INTO "services" ("name","state") VALUES ('receipt-scan', '{"enabled":true,"blockIndex":0,"interval":60000,"step":1,"batchSize":1}');
INSERT INTO "services" ("name","state") VALUES ('token-scan', '{"enabled":true,"blockIndex":0,"interval":60000}');
INSERT INTO "services" ("name","state") VALUES ('rescan-invalid-blocks', '{"pass":1,"enabled":true,"blockIndex":0,"interval":60000}');
INSERT INTO "services" ("name","state") VALUES ('rescan-invalid-receipts', '{"pass":1,"enabled":true,"blockIndex":0,"interval":60000}');
INSERT INTO "services" ("name","state") VALUES ('rescan-invalid-transactions', '{"pass":1,"enabled":true,"blockIndex":0,"interval":60000}');
INSERT INTO "services" ("name","state") VALUES ('scan-missing-blocks', '{"pass":1,"enabled":true,"blockIndex":0,"interval":60000}');
INSERT INTO "services" ("name","state") VALUES ('rescan-transaction-tries', '{"pass":1,"enabled":true,"blockIndex":0,"interval":60000}');
INSERT INTO "services" ("name","state") VALUES ('eth-validate-blocks', '{"pass":1,"enabled":true,"blockIndex":0,"interval":60000,"step":1,"batchSize":1}');